micronaut:
  application:
    name: demo
  openapi:
    views:
      spec: redoc.enabled=true,rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop

  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:swagger
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    dialect: POSTGRES
    schema: app
netty:
  default:
    allocator:
      max-order: 3
azure:
  blob:
    container: ''
    endpoint: 'http://127.0.0.1:10000/devstoreaccount1'
jooq:
  datasources:
    default:
      sql-dialect: 'POSTGRES'

flyway:
  datasources:
    default:
      enabled: true
